#!/bin/bash
# script to allow building of desired sudoku program

if [ "$1" == "all" ]; then
	echo "Building sudoku programs with gtk interface..."
	echo ""
	gcc -o sudoku_gtk sudoku.c main_gtk.c `pkg-config --libs --cflags gtk+-2.0`
	echo ""
	echo "Building sudoku program with command line interface..."
	echo ""
	gcc -Wall -o sudoku_cmd sudoku.c main_cmd.c
elif [ "$1" == "gtk" ]; then
	echo "Building sudoku program with gtk interface..."
	echo ""
	gcc -o sudoku_gtk sudoku.c main_gtk.c `pkg-config --libs --cflags gtk+-2.0`
elif [ "$1" == "cmd" ]; then
	echo "Building sudoku program with command line interface..."
	echo ""
	gcc -Wall -o sudoku_cmd sudoku.c main_cmd.c
elif [ "$1" == "remove" ]; then
	echo "Removing builds..."
	echo ""
	rm -f sudoku_cmd
	rm -f sudoku_gtk
else
	echo "Building script for sudoku programs"
	echo "Options:"
	echo "- gtk - builds sudoku program with gtk interface"
	echo "- cmd - builds sudoku program with command line interface"
	echo "- all - builds both of the above"
	echo "- remove - removes both builds"
fi
